#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6633)

    info( '*** Add switches\n')
    s15 = net.addSwitch('s15', cls=OVSKernelSwitch)
    s14 = net.addSwitch('s14', cls=OVSKernelSwitch)
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)
    s16 = net.addSwitch('s16', cls=OVSKernelSwitch)
    s17 = net.addSwitch('s17', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)
    s5 = net.addSwitch('s5', cls=OVSKernelSwitch)
    s7 = net.addSwitch('s7', cls=OVSKernelSwitch)
    s10 = net.addSwitch('s10', cls=OVSKernelSwitch)
    s8 = net.addSwitch('s8', cls=OVSKernelSwitch)
    s18 = net.addSwitch('s18', cls=OVSKernelSwitch)
    s9 = net.addSwitch('s9', cls=OVSKernelSwitch)
    s19 = net.addSwitch('s19', cls=OVSKernelSwitch)
    s6 = net.addSwitch('s6', cls=OVSKernelSwitch)
    s11 = net.addSwitch('s11', cls=OVSKernelSwitch)
    s13 = net.addSwitch('s13', cls=OVSKernelSwitch)
    s20 = net.addSwitch('s20', cls=OVSKernelSwitch)
    s12 = net.addSwitch('s12', cls=OVSKernelSwitch)

    info( '*** Add hosts\n')
    h1 = net.addHost('h1', cls=Host, ip='10.0.0.2', defaultRoute=None)
    h2 = net.addHost('h2', cls=Host, ip='10.0.0.3', defaultRoute=None)
    h3 = net.addHost('h3', cls=Host, ip='10.0.1.2', defaultRoute=None)
    h4 = net.addHost('h4', cls=Host, ip='10.0.1.3', defaultRoute=None)
    h5 = net.addHost('h5', cls=Host, ip='10.1.0.2', defaultRoute=None)
    h6 = net.addHost('h6', cls=Host, ip='10.1.0.3', defaultRoute=None)
    h7 = net.addHost('h7', cls=Host, ip='10.1.1.2', defaultRoute=None)
    h8 = net.addHost('h8', cls=Host, ip='10.1.1.3', defaultRoute=None)
    h9 = net.addHost('h9', cls=Host, ip='10.2.0.2', defaultRoute=None)
    h10 = net.addHost('h10', cls=Host, ip='10.2.0.3', defaultRoute=None)
    h11 = net.addHost('h11', cls=Host, ip='10.2.1.2', defaultRoute=None)
    h12 = net.addHost('h12', cls=Host, ip='10.2.1.3', defaultRoute=None)
    h13 = net.addHost('h13', cls=Host, ip='10.3.0.2', defaultRoute=None)
    h14 = net.addHost('h14', cls=Host, ip='10.3.0.3', defaultRoute=None)
    h15 = net.addHost('h15', cls=Host, ip='10.3.1.2', defaultRoute=None)
    h16 = net.addHost('h16', cls=Host, ip='10.3.1.3', defaultRoute=None)

    info( '*** Add links\n')
    net.addLink(s3, h1)
    net.addLink(s3, h2)
    net.addLink(s4, h3)
    net.addLink(s4, h4)
    net.addLink(s1, s3)
    net.addLink(s2, s4)
    net.addLink(s1, s4)
    net.addLink(s2, s3)
    net.addLink(s7, h5)
    net.addLink(s7, h6)
    net.addLink(s8, h7)
    net.addLink(s8, h8)
    net.addLink(s11, h9)
    net.addLink(s11, h10)
    net.addLink(s12, h11)
    net.addLink(s12, h12)
    net.addLink(s15, h13)
    net.addLink(s15, h14)
    net.addLink(s16, h15)
    net.addLink(s16, h16)
    net.addLink(s5, s7)
    net.addLink(s6, s8)
    net.addLink(s9, s11)
    net.addLink(s10, s12)
    net.addLink(s13, s15)
    net.addLink(s14, s16)
    net.addLink(s5, s8)
    net.addLink(s6, s7)
    net.addLink(s9, s12)
    net.addLink(s10, s11)
    net.addLink(s13, s16)
    net.addLink(s14, s15)
    net.addLink(s17, s1)
    net.addLink(s17, s5)
    net.addLink(s17, s9)
    net.addLink(s17, s13)
    net.addLink(s18, s1)
    net.addLink(s18, s5)
    net.addLink(s18, s9)
    net.addLink(s18, s13)
    net.addLink(s19, s2)
    net.addLink(s19, s6)
    net.addLink(s19, s10)
    net.addLink(s19, s14)
    net.addLink(s20, s2)
    net.addLink(s20, s6)
    net.addLink(s20, s10)
    net.addLink(s20, s14)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    net.get('s15').start([c0])
    net.get('s14').start([c0])
    net.get('s1').start([c0])
    net.get('s2').start([c0])
    net.get('s3').start([c0])
    net.get('s16').start([c0])
    net.get('s17').start([c0])
    net.get('s4').start([c0])
    net.get('s5').start([c0])
    net.get('s7').start([c0])
    net.get('s10').start([c0])
    net.get('s8').start([c0])
    net.get('s18').start([c0])
    net.get('s9').start([c0])
    net.get('s19').start([c0])
    net.get('s6').start([c0])
    net.get('s11').start([c0])
    net.get('s13').start([c0])
    net.get('s20').start([c0])
    net.get('s12').start([c0])

    info( '*** Post configure switches and hosts\n')
    s1.cmd('ifconfig s1 10.0.2.1')
    s2.cmd('ifconfig s2 10.0.3.1')
    s3.cmd('ifconfig s3 10.0.0.1')
    s4.cmd('ifconfig s4 10.0.1.1')
    s5.cmd('ifconfig s5 10.1.2.1')
    s6.cmd('ifconfig s6 10.1.3.1')
    s7.cmd('ifconfig s7 10.1.0.1')
    s8.cmd('ifconfig s8 10.1.1.1')
    s9.cmd('ifconfig s9 10.2.2.1')
    s10.cmd('ifconfig s10 10.2.3.1')
    s11.cmd('ifconfig s11 10.2.0.1')
    s12.cmd('ifconfig s12 10.2.1.1')
    s13.cmd('ifconfig s13 10.3.2.1')
    s14.cmd('ifconfig s14 10.3.3.1')
    s15.cmd('ifconfig s15 10.3.0.1')
    s16.cmd('ifconfig s16 10.3.1.1')
    s17.cmd('ifconfig s17 10.4.1.1')
    s18.cmd('ifconfig s18 10.4.1.2')
    s19.cmd('ifconfig s19 10.4.2.1')
    s20.cmd('ifconfig s20 10.4.2.2')

    info( '*** Post configure stp \n')
    s1.cmd('ovs-vsctl set bridge s1 stp-enable=true')
    s2.cmd('ovs-vsctl set bridge s2 stp-enable=true')
    s3.cmd('ovs-vsctl set bridge s3 stp-enable=true')
    s4.cmd('ovs-vsctl set bridge s4 stp-enable=true')
    s5.cmd('ovs-vsctl set bridge s5 stp-enable=true')
    s6.cmd('ovs-vsctl set bridge s6 stp-enable=true')
    s7.cmd('ovs-vsctl set bridge s7 stp-enable=true')
    s8.cmd('ovs-vsctl set bridge s8 stp-enable=true')
    s9.cmd('ovs-vsctl set bridge s9 stp-enable=true')
    s10.cmd('ovs-vsctl set bridge s10 stp-enable=true')
    s11.cmd('ovs-vsctl set bridge s11 stp-enable=true')
    s12.cmd('ovs-vsctl set bridge s12 stp-enable=true')
    s13.cmd('ovs-vsctl set bridge s13 stp-enable=true')
    s14.cmd('ovs-vsctl set bridge s14 stp-enable=true')
    s15.cmd('ovs-vsctl set bridge s15 stp-enable=true')
    s16.cmd('ovs-vsctl set bridge s16 stp-enable=true')
    s17.cmd('ovs-vsctl set bridge s17 stp-enable=true')
    s18.cmd('ovs-vsctl set bridge s18 stp-enable=true')
    s19.cmd('ovs-vsctl set bridge s19 stp-enable=true')
    s20.cmd('ovs-vsctl set bridge s20 stp-enable=true')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()
